//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 12:36:37 AM ART 
//


package ajmu.logger.usability;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for logFinalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="logFinalType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="totalExcep" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalDialog" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalAccDoc" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalMessWithoutIcon" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalMessError" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalMessWarn" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalMessInfo" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalMessQuestion" type="{http://www.example.org/usabilityrecord}intType" />
 *       &lt;attribute name="totalExecTime" type="{http://www.example.org/usabilityrecord}longType" />
 *       &lt;attribute name="SatisDegree" type="{http://www.example.org/usabilityrecord}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "logFinalType")
public class LogFinalType {

    @XmlAttribute(name = "totalExcep")
    protected Integer totalExcep;
    @XmlAttribute(name = "totalDialog")
    protected Integer totalDialog;
    @XmlAttribute(name = "totalAccDoc")
    protected Integer totalAccDoc;
    @XmlAttribute(name = "totalMessWithoutIcon")
    protected Integer totalMessWithoutIcon;
    @XmlAttribute(name = "totalMessError")
    protected Integer totalMessError;
    @XmlAttribute(name = "totalMessWarn")
    protected Integer totalMessWarn;
    @XmlAttribute(name = "totalMessInfo")
    protected Integer totalMessInfo;
    @XmlAttribute(name = "totalMessQuestion")
    protected Integer totalMessQuestion;
    @XmlAttribute(name = "totalExecTime")
    protected Long totalExecTime;
    //@XmlAttribute(name = "SatisDegree")
    //protected String satisDegree;
    @XmlAttribute(name = "sat1")
    protected Integer sat1;
    @XmlAttribute(name = "sat2")
    protected Integer sat2;
    @XmlAttribute(name = "sat3")
    protected Integer sat3;
    @XmlAttribute(name = "compositeSat")
    protected Double compositeSat;

    /**
     * Gets the value of the totalExcep property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalExcep() {
        return totalExcep;
    }

    /**
     * Sets the value of the totalExcep property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalExcep(Integer value) {
        this.totalExcep = value;
    }

    /**
     * Gets the value of the totalDialog property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalDialog() {
        return totalDialog;
    }

    /**
     * Sets the value of the totalDialog property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalDialog(Integer value) {
        this.totalDialog = value;
    }

    /**
     * Gets the value of the totalAccDoc property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalAccDoc() {
        return totalAccDoc;
    }

    /**
     * Sets the value of the totalAccDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalAccDoc(Integer value) {
        this.totalAccDoc = value;
    }

    /**
     * Gets the value of the totalMessWithoutIcon property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalMessWithoutIcon() {
        return totalMessWithoutIcon;
    }

    /**
     * Sets the value of the totalMessWithoutIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalMessWithoutIcon(Integer value) {
        this.totalMessWithoutIcon = value;
    }

    /**
     * Gets the value of the totalMessError property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalMessError() {
        return totalMessError;
    }

    /**
     * Sets the value of the totalMessError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalMessError(Integer value) {
        this.totalMessError = value;
    }

    /**
     * Gets the value of the totalMessWarn property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalMessWarn() {
        return totalMessWarn;
    }

    /**
     * Sets the value of the totalMessWarn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalMessWarn(Integer value) {
        this.totalMessWarn = value;
    }

    /**
     * Gets the value of the totalMessInfo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalMessInfo() {
        return totalMessInfo;
    }

    /**
     * Sets the value of the totalMessInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalMessInfo(Integer value) {
        this.totalMessInfo = value;
    }

    /**
     * Gets the value of the totalMessQuestion property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTotalMessQuestion() {
        return totalMessQuestion;
    }

    /**
     * Sets the value of the totalMessQuestion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTotalMessQuestion(Integer value) {
        this.totalMessQuestion = value;
    }

    /**
     * Gets the value of the totalExecTime property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTotalExecTime() {
        return totalExecTime;
    }

    /**
     * Sets the value of the totalExecTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTotalExecTime(Long value) {
        this.totalExecTime = value;
    }
    
    /**
     * Gets the value of the satisDegree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    /*public String getSatisDegree() {
        return satisDegree;
    }*/

    /**
     * Sets the value of the satisDegree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    /*public void setSatisDegree(String value) {
        this.satisDegree = value;
    }*/
    
    /**
     * Gets the value of the compositeSat property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCompositeSat() {
        return compositeSat;
    }

    /**
     * Sets the value of the compositeSat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCompositeSat(double value) {
        this.compositeSat = value;
    }
    
    /**
     * Gets the value of the sat1 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSat1() {
        return sat1;
    }

    /**
     * Sets the value of the sat1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSat1(Integer value) {
        this.sat1 = value;
    }
    

    /**
     * Gets the value of the sat2 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSat2() {
        return sat2;
    }

    /**
     * Sets the value of the sat2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSat2(Integer value) {
        this.sat2 = value;
    }
    

    /**
     * Gets the value of the sat3 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSat3() {
        return sat3;
    }

    /**
     * Sets the value of the sat3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSat3(Integer value) {
        this.sat3 = value;
    }
}
