//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 12:36:37 AM ART 
//


package ajmu.logger.usability;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ajmu.logger.usability package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _UsabilityRecord_QNAME = new QName("http://www.example.org/usabilityrecord", "usabilityRecord");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ajmu.logger.usability
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LogParcialType }
     * 
     */
    public LogParcialType createLogParcialType() {
        return new LogParcialType();
    }

    /**
     * Create an instance of {@link DialogType }
     * 
     */
    public DialogType createDialogType() {
        return new DialogType();
    }

    /**
     * Create an instance of {@link ExceptionType }
     * 
     */
    public ExceptionType createExceptionType() {
        return new ExceptionType();
    }

    /**
     * Create an instance of {@link DialoguesType }
     * 
     */
    public DialoguesType createDialoguesType() {
        return new DialoguesType();
    }

    /**
     * Create an instance of {@link ExceptionsType }
     * 
     */
    public ExceptionsType createExceptionsType() {
        return new ExceptionsType();
    }

    /**
     * Create an instance of {@link TasksAnalizedType }
     * 
     */
    public TasksAnalizedType createTasksAnalizedType() {
        return new TasksAnalizedType();
    }

    /**
     * Create an instance of {@link LogType }
     * 
     */
    public LogType createLogType() {
        return new LogType();
    }

    /**
     * Create an instance of {@link LogFinalType }
     * 
     */
    public LogFinalType createLogFinalType() {
        return new LogFinalType();
    }

    /**
     * Create an instance of {@link SessionType }
     * 
     */
    public SessionType createSessionType() {
        return new SessionType();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link UsabilityRecordType }
     * 
     */
    public UsabilityRecordType createUsabilityRecordType() {
        return new UsabilityRecordType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UsabilityRecordType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.example.org/usabilityrecord", name = "usabilityRecord")
    public JAXBElement<UsabilityRecordType> createUsabilityRecord(UsabilityRecordType value) {
        return new JAXBElement<UsabilityRecordType>(_UsabilityRecord_QNAME, UsabilityRecordType.class, null, value);
    }

}
