//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.19 at 12:36:37 AM ART 
//


package ajmu.logger.usability;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for usabilityRecordType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="usabilityRecordType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tasksAnalized" type="{http://www.example.org/usabilityrecord}tasksAnalizedType"/>
 *         &lt;element name="session" type="{http://www.example.org/usabilityrecord}sessionType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="appName" type="{http://www.example.org/usabilityrecord}stringType" />
 *       &lt;attribute name="version" type="{http://www.example.org/usabilityrecord}stringType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "usabilityRecordType", propOrder = {
    "tasksAnalized",
    "session"
})
public class UsabilityRecordType extends MarshalClass {

    @XmlElement(required = true)
    protected List<TasksAnalizedType> tasksAnalized;
    @XmlElement(required = true)
    protected List<SessionType> session;
    @XmlAttribute(name = "appName")
    protected String appName;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the tasksAnalized property.
     * 
     * @return
     *     possible object is
     *     {@link TasksAnalizedType }
     *     
     */
    public List<TasksAnalizedType> getTasksAnalized() {
    	if (tasksAnalized == null) {
    		tasksAnalized = new ArrayList<TasksAnalizedType>();
        }
        return this.tasksAnalized;
    }

    /**
     * Sets the value of the tasksAnalized property.
     * 
     * @param value
     *     allowed object is
     *     {@link TasksAnalizedType }
     *     
     
    public void setTasksAnalized(TasksAnalizedType value) {
        this.tasksAnalized = value;
    }*/

    /**
     * Gets the value of the session property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the session property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSession().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SessionType }
     * 
     * 
     */
    public List<SessionType> getSession() {
        if (session == null) {
            session = new ArrayList<SessionType>();
        }
        return this.session;
    }

    /**
     * Gets the value of the appName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppName() {
        return appName;
    }

    /**
     * Sets the value of the appName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppName(String value) {
        this.appName = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

}
